### ISSUE TITLE
SSL'li Sitelerde SSL Desteklemeyen Ses Dosyalarının Sorun Çıkarması

### ISSUE THREAD

**Issue by halilselcuk** [halilselcuk/MyBB-Profile-Music-Plugin#1]
SSL'li sitelerde SSL olmayan bir bağlantı eklendiğinde tarayıcı hata veriyor ve ses dosyası yüklenemiyor.

**Comment by MelodicFingers** [comment]
It's an obvious issue, SSL sites are used to show just secure content, if your file is under a normal URL (http://) instead a secured one (https://). I think this mught be the issue but to confirm we will need more details.
