### ISSUE TITLE
Automatically disappeared from usergroup ?

### ISSUE THREAD

**Issue by woovter** [halilselcuk/MyBB-Profile-Music-Plugin#10]
Out of no where the permissions seem to be completely disabled for admin usergroup (to be specific, my account. I'm the only admin), and I had the option in my settings and enabled, but out of no where today it just disappeared from my profile and I can't seem to get the settings in User CP back for it no matter what I do. All other user groups seem to have it just fine and no one else got theirs removed, just me
I already added all the templates and everything. 

Like I said, everything was 100% fine and then out of no where it just deleted itself from my profile & settings

**Comment by halilselcuk** [comment]
Looks like this is bug. When visiting user edit(any user) page on admin panel it removes permission and music link.

Please check your profile from moderator panel for "User can add profile music?" checked or not.

**Comment by woovter** [comment]
> Looks like this is bug. When visiting user edit(any user) page on admin panel it removes permission and music link.
> 
> Please check your profile from moderator panel for "User can add profile music?" checked or not.

Editing user via Mod CP worked. Would have never guessed to check that. Thanks!

**Comment by halilselcuk** [comment]
@NbaYB I fixed this bug. Please update your plugin. Thank you for your contribution. :)
