### ISSUE TITLE
plugin breaks mybb profile pages

### ISSUE THREAD

**Issue by monke1727sirmud** [halilselcuk/MyBB-Profile-Music-Plugin#11]
I had trouble getting it to work with curl and decided to deactivate it. that's when it broke my forum profile pages including the profile editor settings page. those pages are blank when broken.

**Comment by halilselcuk** [comment]
Hi, thank you for sharing your problem. I have update the plugin. Please try install or upgrade. If your problem persists please share info about your PHP server.
