### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by monavdyli** [halilselcuk/MyBB-Profile-Music-Plugin#12]
It seems that this plugin is outdated 
Please wait until the author updates it
other wise u gonna break ur forum

**Comment by monavdyli** [comment]
Actually it deletes all your Member profile page and Usercp page 
Just delete this plugin please

**Comment by halilselcuk** [comment]
Hi, thank you for sharing your problem. I have update the plugin. Please try install or upgrade. If your problem persists please share info about your PHP server.
