### ISSUE TITLE
Music only working on default theme?

### ISSUE THREAD

**Issue by forid786** [halilselcuk/MyBB-Profile-Music-Plugin#2]
Music not playing on custom templates even after clicking "add template code" in the plugins manager in ACP.

**Comment by halilselcuk** [comment]
Add template code feature not compatible all themes. Try it manually:
https://github.com/halilselcuk/MyBB-Profile-Music-Plugin/wiki/Theme-Change

**Comment by forid786** [comment]
Thanks bro, exactly what I needed. :)
