### ISSUE TITLE
Problem with

### ISSUE THREAD

**Issue by Kelysha** [halilselcuk/MyBB-Profile-Music-Plugin#3]
Hello, your plugin was created a long time ago, I hope still get an answer from you.

I installed the plugin, in the settings I can add a link youtube but when I go on my profile, it does not display anything at all.

http://cbutterfly.com/member.php?action=profile&uid=33

Thanks you.. I hope to get an answer

**Comment by halilselcuk** [comment]
Hello, looks like profile music code not added to the member_profile template. 

Please check your member_profile template.
https://github.com/halilselcuk/MyBB-Profile-Music-Plugin/wiki/Potential-Problems
https://github.com/halilselcuk/MyBB-Profile-Music-Plugin/wiki/Theme-Change
