### ISSUE TITLE
Profile Music Usergroup Setting is set to 0 after saving

### ISSUE THREAD

**Issue by MelodicFingers** [halilselcuk/MyBB-Profile-Music-Plugin#4]
I can activate the plugin and use it, but it gets automatically deativated (in the edited usergroup) after you save usergroup setting changes, once this happens, even if you try to re-check the box to reactivate it, it just fails to re-activate the rights on that usergroup.

**Comment by halilselcuk** [comment]
Thank you for your contribution. I fixed it.

**Comment by MelodicFingers** [comment]
Thanks a lot I am expecting to use this plugin for a project.

**Comment by kluczewp** [comment]
dont work. latest ver
