### ISSUE TITLE
Profile music player

### ISSUE THREAD

**Issue by kluczewp** [halilselcuk/MyBB-Profile-Music-Plugin#6]
Profile music player doesnt work. 
where exactly should I insert this code? {$profilmuzigi}
Could you explain me step by step?

**Comment by halilselcuk** [comment]
See here. 
https://github.com/halilselcuk/MyBB-Profile-Music-Plugin/wiki/Theme-Change#if-you-cant-see-profile-music-player-on-user-profile

If you use default profile template add under {$userstars}.

**Comment by kluczewp** [comment]
![errors](https://user-images.githubusercontent.com/35502551/37051173-02449b56-2176-11e8-887b-8145bbd6e334.jpg)

Done. And i Have this errors??

**Comment by halilselcuk** [comment]
Please update plugin. I have updated now.

**Comment by kluczewp** [comment]
Then you again for your patient. I've updated. I've add code. No errors :D. 
But still no working. Any ideas?
![edit_profile](https://user-images.githubusercontent.com/35502551/37099511-c2f3267e-2220-11e8-91b0-6fc4834ad4d0.jpg)
![edit_profile2](https://user-images.githubusercontent.com/35502551/37099514-c514a8e2-2220-11e8-83eb-ec2d8fd8050c.jpg)
![doest_work](https://user-images.githubusercontent.com/35502551/37099519-c9fa620c-2220-11e8-94b5-9849107d7e21.jpg)
![member_profile](https://user-images.githubusercontent.com/35502551/37099532-d2bc7b6e-2220-11e8-983f-1d06fa641763.jpg)

**Comment by halilselcuk** [comment]
It's only works on profiles. Like this. :)
https://demomybb.tk/user-1.html

And you can edit profile music from "User CP -> Edit Profile" page.

This is not what you want. :)
