### ISSUE TITLE
Hello, i have an issue with the plugin

### ISSUE THREAD

**Issue by FlatoutDude** [halilselcuk/MyBB-Profile-Music-Plugin#8]
so, i've downloaded the plugin, and when go into my User CP, there are 3 options to place a music URL, i don't know if this is intended, but when i put 3 seperate URLs, only one song appears on my pfp, when i go back, all the urls are the same.

**Comment by FlatoutDude** [comment]
[https://i.imgur.com/qnonxub.png](url)

**Comment by halilselcuk** [comment]
Hello, please try deactivate&activate plugin. Plugin is compatible with only 1 input.
